name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # scan_ruby:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         bundler-cache: true

  #     - name: Scan for security vulnerabilities in Ruby dependencies
  #       run: |
  #         bundle exec bundler-audit --update
  #         bin/brakeman -q -w2 --no-pager

  lint:
    runs-on: ubuntu-latest

    env:
      DISABLE_BOOTSNAP: true
      DISABLE_BOOTSNAP_LOAD_PATH_CACHE: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run linters
        run: bin/rubocop --parallel
